___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
array1 = np.ones((4,4), dtype=int)
array1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [5]:
array1[:,:]=7
array1

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [6]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [7]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [8]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create 5 random number with numpy

In [10]:
np.random.rand(5)

array([0.66096399, 0.99853172, 0.4005207 , 0.28274977, 0.71586828])

#### 11. Create random normal distributed 5x5 array

In [11]:
np.random.rand(5,5)

array([[0.28705231, 0.14397642, 0.1444364 , 0.8541816 , 0.91852951],
       [0.11913   , 0.53423376, 0.13564897, 0.7086191 , 0.88759514],
       [0.24367996, 0.92451423, 0.57863222, 0.87325763, 0.55484593],
       [0.71841855, 0.59297658, 0.01167605, 0.79595966, 0.15884887],
       [0.23321665, 0.22329782, 0.24500737, 0.18996061, 0.39140542]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [12]:
np.random.randint(20,50,size=(3,4))

array([[40, 42, 30, 34],
       [39, 21, 48, 38],
       [21, 42, 25, 40]])

#### 13. Reshape the array below with shape 6x8

In [13]:
ranarr=[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]

In [14]:
ranarr = np.array(ranarr)
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [15]:
ranarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [16]:
np.array(ranarr).reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [17]:
#reshape with -1
ranarr.reshape(-1,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [18]:
#Create array below
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [19]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [20]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [21]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [22]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [23]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [25]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [26]:
new_arr1 = mat[[1,1],[0,2]]
new_arr2 = mat[[3,3],[0,2]]
new_arr = np.concatenate(([new_arr1], [new_arr2]),axis=0)
new_arr

array([[ 5, 77],
       [13, 77]])

In [27]:
new_arr = np.concatenate(([mat[[1,1],[0,2]]], [mat[[3,3],[0,2]]]),axis=0)
new_arr

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [28]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [29]:
a=mat[mat<10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [30]:
b=mat[mat>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [31]:
arr_sum = a+b
arr_sum

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [32]:
np.std(arr_sum)

29.700546274093877

#### 22. Get the sum of second column from array above

In [33]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [34]:
np.sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [35]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [36]:
mat[2]

array([ 9, 10, 77, 12])

In [37]:
#median
np.median(mat[2])

11.0

In [38]:
#mean
np.mean(mat[2])

27.0

In [39]:
#std
np.std(mat[2])

28.88771365130858

# Pandas Section

In [40]:
import pandas as pd

In [41]:
from google.colab import drive
drive.mount('/content/drive')       # csv dosyasını drive a kopyalıyoruz. drive ı mount ediyoruz

Mounted at /content/drive


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [42]:
sal=pd.read_csv('/content/drive/MyDrive/Salaries.csv')   # csv dosyasını okutturuyoruz

In [70]:
sal.head()     # tablonun ilk beş satırını getirmesini istiyoruz

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [44]:
sal.info()    # tablodaki veri sütunlarını, indekslerini ve tiplerini görmek için kullanıyoruz

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [68]:
sal.describe()    # tablodaki veri sütunlarını, istatistiksel numerik değerleri görmek için kullanıyoruz

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

---



In [46]:
years =  sal['Year'].value_counts()     # tablodaki bir sütunun distinct değerlerini saydırıyoruz
years

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [75]:
years = sal.Year.value_counts()
years

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [79]:
#max
max(sal.TotalPay)               # maksimum değerler için

567595.43

In [48]:
#avg
sal["TotalPay"].mean()           # ortalama değerler için

74768.321971703

In [81]:
sal.TotalPay.mean()      # sütun ismi içerisinde boşluk ya da nokta varsa bu şekilde yazılmaz

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [49]:
records = sal[sal['TotalPay'] > sal['TotalPay'].mean()].TotalPay
records.count()                                                       # ücret karşılaştırması, ortalamadan büyük ücret alan kayıt bilgilerinin getirilmesi

69489

In [85]:
records = sal[sal['TotalPay'] > sal['TotalPay'].mean()]['TotalPay']
records.count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [50]:
sal[sal['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']    # ALBERT PARDINI isimli şahsın kazancını buldurma

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [86]:
sal['EmployeeName'] == 'ALBERT PARDINI'

0         False
1         False
2          True
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

In [89]:
sal[sal["EmployeeName"]=="ALBERT PARDINI"]

Id    EmployeeName  ...         Agency  Status
2   3  ALBERT PARDINI  ...  San Francisco     NaN

[1 rows x 13 columns]

In [97]:
sal["EmployeeName"].isin(["ALBERT PARDINI"])

0         False
1         False
2          True
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

**Who is lowest paid person**

In [51]:
sal["EmployeeName"][sal["TotalPay"]== min(sal["TotalPay"])]      # en az ücret alan kişi

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [98]:
sal[sal["TotalPay"]== min(sal["TotalPay"])]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [99]:
sal.loc[sal["TotalPay"].idxmin()]["EmployeeName"]

'Joe Lopez'

In [100]:
sal.loc[sal["TotalPay"].idxmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                      0
OvertimePay                                  0
OtherPay                               -618.13
Benefits                                     0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

In [101]:
sal["TotalPay"].idxmin()

148653

In [103]:
sal.iloc[sal["TotalPay"].idxmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                      0
OvertimePay                                  0
OtherPay                               -618.13
Benefits                                     0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

**What are the unique Jobs in dataset?**

In [113]:
sal["JobTitle"].unique()              # unique meslekler

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [114]:
sal['JobTitle'].value_counts().tail(3)                              # listedeki en az rastlanan 3 meslek    

PORT DIRECTOR                                      1
HEAVY EQUIPMENT OPERATIONS ASSISTANT SUPERVISOR    1
TELECOMMUNICATIONS TECHNICIAN SUPERVISOR           1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [128]:
sal[(sal["Year"]==2012)&(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].mean())]["Id"].count()

20366

In [135]:
len(sal[sal["TotalPayBenefits"]>sal["TotalPayBenefits"].mean()].loc[sal['Year'] == 2012])

20366

**How many people have the word Manager in their job title?**

In [141]:
#use apply function here                                   Kaç kişinin iş unvanında Yönetici kelimesi var?
def chief_string(title):
    if 'manager' in title.lower():
        return True
    else:
        return False

sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

4110

In [143]:
sum(sal['JobTitle'].apply(chief_string))

4110

In [145]:
sum(map(chief_string,sal['JobTitle']))

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [56]:
sal.info()                                   # önce hangi sütun hangi indekste bakıyoruz   

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [57]:
sal_new=sal.iloc[:,[1,2,7,8]]                  # sonra iloc olduğu için indeksleri çağırıyoruz
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [149]:
sal_new=sal.loc[:, ['EmployeeName','JobTitle','BasePay','OvertimePay','OtherPay','Benefits','TotalPay','TotalPayBenefits']]     # loc olduğu için label ları ile çağırıyoruz
sal_new

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 8 columns]

In [153]:
sal_new2=sal.iloc[:,1:9]
sal_new2

EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [59]:
sal[sal['TotalPayBenefits'] > sal['TotalPayBenefits'].min()]             # minimumdan fazla kazananların olduğu kayıtlar

Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148648  148649        Leon Walker  ...  San Francisco     NaN
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN

[148653 rows x 13 columns]

In [60]:
sal[sal['TotalPayBenefits'] < sal['TotalPayBenefits'].mean()]         # ortalamadan fazla kazananların olduğu kayıtlar

Id    EmployeeName  ...         Agency  Status
10806    10807         KWE LEE  ...  San Francisco     NaN
10807    10808  MIGUEL CARO JR  ...  San Francisco     NaN
10808    10809   JOANNE MORRIS  ...  San Francisco     NaN
10809    10810   LAYLA WELBORN  ...  San Francisco     NaN
10810    10811         LE BANH  ...  San Francisco     NaN
...        ...             ...  ...            ...     ...
148649  148650   Roy I Tillery  ...  San Francisco     NaN
148650  148651    Not provided  ...  San Francisco     NaN
148651  148652    Not provided  ...  San Francisco     NaN
148652  148653    Not provided  ...  San Francisco     NaN
148653  148654       Joe Lopez  ...  San Francisco     NaN

[75650 rows x 13 columns]

In [61]:
sal[sal.TotalPayBenefits > sal.TotalPayBenefits.min()]             # minimumdan fazla kazananların olduğu kayıtların bir başka şekilde çağrılması

Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148648  148649        Leon Walker  ...  San Francisco     NaN
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN

[148653 rows x 13 columns]

In [62]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]    # ikinci sorgu şekli kullanılarak çoklu sorgunun yapılması

Id    EmployeeName  ...         Agency  Status
10806    10807         KWE LEE  ...  San Francisco     NaN
10807    10808  MIGUEL CARO JR  ...  San Francisco     NaN
10808    10809   JOANNE MORRIS  ...  San Francisco     NaN
10809    10810   LAYLA WELBORN  ...  San Francisco     NaN
10810    10811         LE BANH  ...  San Francisco     NaN
...        ...             ...  ...            ...     ...
148648  148649     Leon Walker  ...  San Francisco     NaN
148649  148650   Roy I Tillery  ...  San Francisco     NaN
148650  148651    Not provided  ...  San Francisco     NaN
148651  148652    Not provided  ...  San Francisco     NaN
148652  148653    Not provided  ...  San Francisco     NaN

[75649 rows x 13 columns]

In [154]:
sal[(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].min()) & (sal["TotalPayBenefits"]<sal["TotalPayBenefits"].mean())][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]

In [155]:
sal[(sal["TotalPayBenefits"]>sal["TotalPayBenefits"].min()) & (sal["TotalPayBenefits"]<sal["TotalPayBenefits"].mean())]["EmployeeName"]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object