## Descriptive Statistics



```
# Bu, kod olarak biçimlendirilmiştir
```

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
from scipy import stats
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=1000)

In [ ]:
ornek = np.array([7,7,6,5,5,8,8,8,8])
ornek

array([7, 7, 6, 5, 5, 8, 8, 8, 8])

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

In [ ]:
print(mean)
print(median)
print(mode)

98.97219878142833
98.78325231057144
ModeResult(mode=array([47.98492759]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = samples.min()
max = samples.max()
q1 = np.median(samples[:500])
q3 = np.median(samples[500:])
iqr = q3 - q1

In [ ]:
print(min)
print(max)
print(q1)
print(q3)
print(iqr)

47.984927588523085
142.3909959751683
98.74582639538234
98.83513799966495
0.08931160428261364


Compute the **variance** and **standard deviation**

In [ ]:
import statistics
variance = statistics.variance(samples)
std_dev = statistics.stdev(samples)
variance

232.8605596972087

In [ ]:
import numpy as np

In [ ]:
var = np.var(samples)
var

232.62769913751148

In [ ]:
standart = np.std(samples)
standart

15.252137526835755

In [ ]:
print(variance)
print(std_dev)

232.8605596972087
15.259769319921213


In [ ]:
mod = statistics.mode(ornek)
mod

8

In [ ]:
mod2 = stats.mode(ornek)
mod2

ModeResult(mode=array([8]), count=array([4]))

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)

In [ ]:
print(skewness)
print(kurtosis)

-0.05946637799549916
-0.04322907892799677


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10, 20)

In [ ]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)

In [ ]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
x
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = x.corr(y)

In [ ]:
r

0.7586402890911867

In [ ]:
r1 = y.corr(x)
r1

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = x.corr(y, method='spearman')

In [ ]:
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000